### PR TITLE
File Logging Removal

### PR DESCRIPTION
**Pull request by powergiggs**
I remove the file logging feature and minor tweak to read me, let me know what you

### CODE REVIEW

**Comment by ECorreia45** [comment]
You actually change an old version. I forgot to do another version release. One question. Why remove the log to file feature?

**Comment by powergiggs** [comment]
that feature is no longer needed and remember is not a part of the 12 factor App Manifesto the server does that automatically.

**Comment by ECorreia45** [comment]
Yeah, i did not read the assignment details thats why...good looks

**Comment by powergiggs** [comment]
Ok great

**Comment by powergiggs** [comment]
great!!!

**Pull request merged**
